"""initial_schema

Revision ID: a601889e1b84
Revises: 
Create Date: 2026-07-29 19:00:01.552833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a601889e1b84'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('insights', 'supporting_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('precision_engine_config', 'decay_const',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Eksponensial pasayish doirasi (0.01-1.0)',
               existing_nullable=False,
               existing_server_default=sa.text("'0.05'::double precision"))
    op.alter_column('precision_engine_config', 'early_bonus_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Erta bajarish bonusi stavkasi (0.0-0.1)',
               existing_nullable=False,
               existing_server_default=sa.text("'0.01'::double precision"))
    op.alter_column('precision_engine_config', 'bonus_cap',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Maksimal bonus chegarasi (0.0-0.5)',
               existing_nullable=False,
               existing_server_default=sa.text("'0.15'::double precision"))
    op.alter_column('precision_engine_config', 'tolerance_default',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Standart tolerantlik (daqiqa)',
               existing_nullable=False,
               existing_server_default=sa.text("'10'::double precision"))
    op.alter_column('precision_engine_config', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Faol konfiguratsiya',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('precision_engine_config', 'version',
               existing_type=sa.VARCHAR(length=50),
               comment='Konfiguratsiya versiyasi',
               existing_nullable=False,
               existing_server_default=sa.text("'1'::character varying"))
    op.alter_column('progress_snapshots', 'breakdown',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_referrals_code'), table_name='referrals')
    op.alter_column('score_events', 'calculation_meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_subscriptions_tier'), table_name='subscriptions')
    op.drop_constraint(op.f('user_sessions_refresh_token_jti_key'), 'user_sessions', type_='unique')
    op.create_index(op.f('ix_user_sessions_refresh_token_jti'), 'user_sessions', ['refresh_token_jti'], unique=True)
    op.alter_column('users', 'notification_prefs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('users_telegram_id_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=False)
    op.create_unique_constraint(op.f('users_telegram_id_key'), 'users', ['telegram_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'notification_prefs',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_user_sessions_refresh_token_jti'), table_name='user_sessions')
    op.create_unique_constraint(op.f('user_sessions_refresh_token_jti_key'), 'user_sessions', ['refresh_token_jti'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_subscriptions_tier'), 'subscriptions', ['tier'], unique=False)
    op.alter_column('score_events', 'calculation_meta',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_referrals_code'), 'referrals', ['code'], unique=False)
    op.alter_column('progress_snapshots', 'breakdown',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('precision_engine_config', 'version',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Konfiguratsiya versiyasi',
               existing_nullable=False,
               existing_server_default=sa.text("'1'::character varying"))
    op.alter_column('precision_engine_config', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Faol konfiguratsiya',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('precision_engine_config', 'tolerance_default',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Standart tolerantlik (daqiqa)',
               existing_nullable=False,
               existing_server_default=sa.text("'10'::double precision"))
    op.alter_column('precision_engine_config', 'bonus_cap',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Maksimal bonus chegarasi (0.0-0.5)',
               existing_nullable=False,
               existing_server_default=sa.text("'0.15'::double precision"))
    op.alter_column('precision_engine_config', 'early_bonus_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Erta bajarish bonusi stavkasi (0.0-0.1)',
               existing_nullable=False,
               existing_server_default=sa.text("'0.01'::double precision"))
    op.alter_column('precision_engine_config', 'decay_const',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Eksponensial pasayish doirasi (0.01-1.0)',
               existing_nullable=False,
               existing_server_default=sa.text("'0.05'::double precision"))
    op.alter_column('insights', 'supporting_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
